export interface Movie {
  id: string; // can be "movie_id" or "tv_id" or simple id
  title: string;
  type: 'movie' | 'tv';
  category?: 'trending_movies' | 'popular_movies' | 'top_rated_movies' | 'trending_tv' | 'popular_tv' | 'top_rated_tv';
  year: number;
  rating: number; // TMDB rating
  genres: string[];
  description: string;
  poster: string;
  backdrop?: string;
  stars?: string[];
  trailer?: string; // YouTube embed Key
}

export interface UserStats {
  watchlistCount: number;
  watchedCount: number;
  watchingCount: number;
  totalHoursWatched: number;
  averageRating: number;
}

export type TrackStatus = 'watched' | 'watching' | 'plan_to_watch';

export interface TrackedItem {
  id: string; // unique auth userId + "_" + itemId or firestore autogenerated doc id
  userId: string;
  itemId: string; // original TMDB/catalog movie id (e.g., movie_123 or tv_456)
  title: string;
  type: 'movie' | 'tv';
  status: TrackStatus;
  
  // Model fields from user request:
  // For 'watched' status
  userRating?: number; // scale 1-10
  review?: string;
  dateWatched?: string; // ISO date string or YYYY-MM-DD
  favoriteScenes?: string[];
  rewatchCount?: number;
  notes?: string;

  // For 'watching' status
  episodeProgress?: number;
  seasonProgress?: number;
  timeRemaining?: string; // e.g. "20 mins"

  // For 'plan_to_watch' status
  priority?: 'low' | 'medium' | 'high';
  personalTags?: string[];
  estimatedWatchTime?: number; // in mins

  updatedAt: string;
}

export interface UserPreferences {
  preferredVibe?: string;
  username?: string;
  avatarUrl?: string;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  unlockedAt?: string;
  iconName: string;
}

export interface AIRecommendation {
  title: string;
  reason: string;
  genre: string;
}
